modLoader = "javafml"
loaderVersion = ">=${forge_version}"
license = "${mod_license}"
issueTrackerURL = "${git_repository_host}/${git_organization}/${mod_id}/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "Steveplays28"
description = '''
${mod_description}
'''
logoFile = "assets/${mod_id}/icon.png"
displayURL = "https://github.com/steves-underwater-paradise/${mod_id}"
acceptableRemoteVersions = "${major_version}.x.x"

[mc-publish]
loaders = ["forge", "neoforge"]
curseforge = "${curseforge_project_id}"
modrinth = "${modrinth_project_id}"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${supported_minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = ">=${forge_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "distanthorizons"
mandatory = true
versionRange = ">=2.1.3-a-dev"
ordering = "NONE"
side = "CLIENT"
